name: scheduled-data-update
run-name: Scheduled update of data
on:
  schedule:
    - cron:  '15 0 * * *'
  workflow_dispatch:
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch new data
        shell: bash
        run: |
          echo "::group::Fetching data from obsidian-releases"
          mkdir fetch
          cd fetch
          git clone https://github.com/obsidianmd/obsidian-releases.git .
          cp community-plugins.json ../community-plugins.json
          
          echo "Extracting history of community-plugin-stats.json"
          LOG_COUNT=$(git log --oneline -- community-plugin-stats.json | wc -l)
          echo "Found $LOG_COUNT historical versions of community-plugin-stats.json"
          
          CURRENT=0
          git log --reverse --pretty=format:"%at %H" -- community-plugin-stats.json | while read ts hash; do
            echo "---BEGIN $ts---"
            git show $hash:community-plugin-stats.json
            echo "---END---"
            CURRENT=$((CURRENT+1))
            if (( CURRENT % 100 == 0 )); then
              echo "::notice::Extracted $CURRENT/$LOG_COUNT versions..." >&2
            fi
          done > ../stats.json
          echo "Finished extraction."
          cd ..
          rm -rf fetch
          echo "::group::Final stats file size"
          ls -lh ${{ github.workspace }}/stats.json
          echo "::endgroup::"
          echo "::endgroup::"
      - name: Check out main
        with:
          ref: main
          path: 'crunch'
        uses: actions/checkout@v3
      - name: Crunch data into fitting format
        shell: bash
        run: |
          echo "::group::Crunching data"
          cd crunch
          cp -R ./script/crunch/. .
          cp ../stats.json ./stats.json
          cp ../community-plugins.json ./community-plugins.json
          echo "Starting Go cruncher..."
          time go run crunch.go
          
          echo "Moving results to data directory"
          mkdir ${{ github.workspace }}/data
          cp plugins.json ../data/plugins.json
          cp -R ./plugins/. ../data/plugins
          cd ..
          rm -rf crunch
          echo "::endgroup::"
      - name: Check out gh-pages
        with:
          ref: gh-pages
          path: 'deploy'
        uses: actions/checkout@v3
      - name: Commit new data
        shell: bash
        run: |
          echo "Crunch data into fitting format"
          cd ${{ github.workspace }}/deploy
          git config --global user.name "nevernotmove-bot"
          git config --global user.email "nevernotmove@gmail.com"
          echo "Deleting old data"
          rm -rf ./data
          echo "Adding new data"
          cp -R ../data ./data
          git add ./data
          git commit -m 'Auto deploy new data'
          git status
      - name: Push data to GitHub page
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          directory: deploy