name: scheduled-data-update
run-name: Scheduled update of data
on:
  schedule:
    - cron:  '15 0 * * *'
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch new data
        shell: bash
        run: |
          echo "Fetch new data"
          mkdir fetch
          cd fetch
          git clone https://github.com/obsidianmd/obsidian-releases.git .
          cp community-plugins.json ../community-plugins.json
          git fast-export --all community-plugin-stats.json >> ../stats.json
          cd ..
          rm -rf fetch
          ls ${{ github.workspace }}
      - name: Check out main
        with:
          ref: main
          path: 'crunch'
        uses: actions/checkout@v3
      - name: Crunch data into fitting format
        shell: bash
        run: |
          echo "Crunch data into fitting format"
          cd crunch
          cp -R ./script/crunch/. .
          cp ../stats.json ./stats.json
          go mod vendor
          go run crunch.go
          mkdir ${{ github.workspace }}/data
          cp plugins.json ../data/plugins.json
          cp -R ./plugins/. ../data/plugins
          cd ..
          rm -rf crunch
          ls ${{ github.workspace }}
      - name: Check out gh-pages
        with:
          ref: gh-pages
          path: 'deploy'
        uses: actions/checkout@v3
      - name: Commit new data
        shell: bash
        run: |
          echo "Crunch data into fitting format"
          cd ${{ github.workspace }}/deploy
          git config --global user.name "nevernotmove-bot"
          git config --global user.email "nevernotmove@gmail.com"
          echo "Deleting old data"
          rm -rf ./data
          echo "Adding new data"
          cp -R ../data ./data
          git add ./data
          git commit -m 'Auto deploy new data'
          git status
      - name: Push data to GitHub page
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          directory: deploy