name: Update Data
run-name: Scheduled update of data
on:
  schedule:
    - cron:  '20 23 * * *'
jobs:
  Update-Data:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch new data
        shell: bash
        run: |
          echo "Fetch new data"
          mkdir fetch
          cd fetch
          git clone https://github.com/obsidianmd/obsidian-releases.git .
          git fast-export --all community-plugin-stats.json >> ../stats.json
          cd ..
          rm -rf fetch
          ls ${{ github.workspace }}
      - name: Check out main
        with:
          ref: main
          path: 'crunch'
        uses: actions/checkout@v3
      - name: Crunch data into fitting format
        shell: bash
        run: |
          echo "Crunch data into fitting format"
          cd crunch
          cp -R ./script/crunch/. .
          cp ../stats.json ./stats.json
          go mod vendor
          go run crunch.go
          mkdir ${{ github.workspace }}/data
          cp total-downloads.json ../data/total-downloads.json
          cp -R ./plugins/. ../data/plugins
          cd ..
          rm -rf crunch
          ls ${{ github.workspace }}
      - name: Check out gh-pages
        with:
          ref: gh-pages
          path: 'deploy'
        uses: actions/checkout@v3
      - name: Commit new data
        shell: bash
        run: |
          echo "Crunch data into fitting format"
          cd ${{ github.workspace }}/deploy
          git config --global user.name "github-action"
          git config --global user.email "github-action@nevernotmove-no-reply.com"
          rm -rf ./plugins
          rm ./total-downloads.json
          cp ../data/total-downloads.json ./total-downloads.json
          cp -R ../data/plugins/. ./plugins
          git add total-downloads.json ./plugins/*
          git commit -m 'Deploy new data'
          git status
      - name: Push data to GitHub page
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          directory: deploy